require('../out/runtime/package');
System.import('cyclic/cyclic')
    .then(function(r){
        console.info(JSON.stringify(System.modules,null,2));
    })
    .catch(function(e){
        console.error(e.stack)
    })
;