/// <reference no-default-lib="true"/>
/// <reference path="lib.es5.ts" />
/// <reference path="lib.es2015.core.ts" />
/// <reference path="lib.es2015.collection.ts" />
/// <reference path="lib.es2015.generator.ts" />
/// <reference path="lib.es2015.iterable.ts" />
/// <reference path="lib.es2015.promise.ts" />
/// <reference path="lib.es2015.proxy.ts" />
/// <reference path="lib.es2015.reflect.ts" />
/// <reference path="lib.es2015.symbol.ts" />
/// <reference path="lib.es2015.symbol.wellknown.ts" />
/// <reference path="lib.es2016.array.include.ts" />
/// <reference path="lib.es2017.object.ts" />
/// <reference path="lib.es2017.sharedmemory.ts" />
/// <reference path="lib.es2017.string.ts" />
/// <reference path="lib.es2017.intl.ts" />
/// <reference path="lib.esnext.asynciterable.ts" />
/// <reference path="lib.extras.ts" />